dr_go/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name='main'
urlpatterns = [
    path('',views.index, name="index"),
    # path('about/',views.about,name='about'),
    path('blog/',views.blog,name='blog'),
    path('listing/',views.listing,name='listing'), #나중에 없앨것
    path('main/',views.main,name='main'),
    path('single/',views.single,name='single'),
    path('testimonials/',views.testimonials,name='testimonials'),
    path('contact/',views.contact,name='contact'),
    path('xlsx/',views.xlsx, name='xlsx'),

    path('cities',views.read_city_list,name='read_city_list'),
    path('cities/<str:city>/hospitals',views.read_hospital_list,name='read_hospital_list'),
    path('cities/<str:city>/hospitals/<int:hospital_id>/subjects',views.read_subjects_list,name='read_subjects_list'),
    path('about/<int:subjects_id>',views.about,name='about'),
    path('review/<int:subjects_id>',views.review,name='review'),
    path('review/<int:subjects_id>',views.add_review, name="add_review"),
    
    path('city_list/',views.read_city_list,name='city_list'),  #index.html
    path('<str:city>/hospital_list',views.read_hospital_list,name='hospital_list'),
    path('<int:hospital_id>/subjects_list',views.read_subjects_list,name='read_subjects_list'),
    path('about/<int:subjects_id>',views.about, name='about'),
    path('listing/cities/<str:city>/hospitals', views.listing_hospital, name='listing_hospital'),
    path('cities/all/hospitals', views.listing_all, name='listing_all'),
    


]
# http://127.0.0.1:8000/main/country/
# http://127.0.0.1:8000/main/all/
# http://127.0.0.1:8000/main/seoul/
# http://127.0.0.1:8000/main/about/70

users/urls.py
from django.urls import path
from . import views

app_name='users'
urlpatterns = [
    path('sign_up/',views.sign_up,name='sign_up'),
    path('login/',views.login,name='login'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>DR.GO &mdash; 낭만닥터 고사부</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href='{% static "fonts/icomoon/style.css" %}'>
    <link rel="stylesheet" href='{% static "css/bootstrap.min.css" %}'>
    <link rel="stylesheet" href='{% static "css/bootstrap-datepicker.css" %}'>
    <link rel="stylesheet" href='{% static "css/jquery.fancybox.min.css" %}'>
    <link rel="stylesheet" href='{% static "css/owl.carousel.min.css" %}'>
    <link rel="stylesheet" href='{% static "css/owl.theme.default.min.css" %}'>
    <link rel="stylesheet" href='{% static "fonts/flaticon/font/flaticon.css" %}'>
    <link rel="stylesheet" href='{% static "css/aos.css" %}'>

    <!-- MAIN CSS -->
    <link rel="stylesheet" href='{% static "css/style.css" %}'>

    <!-- JQuery -->
    <script src='{% static "js/jquery-3.3.1.min.js" %}'></script>
    {% block style %}
    {% endblock %}
</head>


<body>
    <div class="site-wrap" id="home-section">

        <div class="site-mobile-menu site-navbar-target">
            <div class="site-mobile-menu-header">
                <div class="site-mobile-menu-close mt-3">
                    <span class="icon-close2 js-menu-toggle"></span>
                </div>
            </div>
            <div class="site-mobile-menu-body"></div>
        </div>



        <header class="site-navbar site-navbar-target" role="banner">

            <div class="container">
                <div class="row align-items-center position-relative">

                    <div class="col-3">
                        <div class="site-logo">
                            <a href='{% url "main:index" %}'><strong>DR.GO</strong></a>
                        </div>
                    </div>

                    <div class="col-9  text-right">

                        <span class="d-inline-block d-lg-none"><a href="#"
                                class=" site-menu-toggle js-menu-toggle py-5 "><span
                                    class="icon-menu h3 text-black"></span></a></span>

                        <nav class="site-navigation text-right ml-auto d-none d-lg-block" role="navigation">
                            <ul class="site-menu main-menu js-clone-nav ml-auto ">
                                <li><a href='{% url "main:index" %}' class="nav-link">Home</a></li>
                                <li><a href='{% url "main:listing" %}' class="nav-link">Listing</a></li>
                                <li><a href='{% url "main:testimonials" %}' class="nav-link">Subject</a></li>
                                <li><a href='{% url "main:blog" %}' class="nav-link">Review</a></li>
                                {#<li class="active"><a href='{% url "main:about" %}' class="nav-link">About</a></li>#}
                                <li><a href='{% url "users:sign_up" %}' class="nav-link">Sign Up</a></li>
                            </ul>
                        </nav>
                    </div>


                </div>
            </div>

        </header>
        {% block content %}
        {% endblock %}
        <footer class="site-footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3">
                        <h2 class="footer-heading mb-4">About Us</h2>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia,
                            there live the
                            blind texts. </p>
                        <ul class="list-unstyled social">
                            <li><a href="#"><span class="icon-facebook"></span></a></li>
                            <li><a href="#"><span class="icon-instagram"></span></a></li>
                            <li><a href="#"><span class="icon-twitter"></span></a></li>
                            <li><a href="#"><span class="icon-linkedin"></span></a></li>
                        </ul>
                    </div>
                    <div class="col-lg-8 ml-auto">
                        <div class="row">
                            <div class="col-lg-3">
                                <h2 class="footer-heading mb-4">Quick Links</h2>
                                <ul class="list-unstyled">
                                    <li><a href="#">About Us</a></li>
                                    <li><a href="#">Testimonials</a></li>
                                    <li><a href="#">Terms of Service</a></li>
                                    <li><a href="#">Privacy</a></li>
                                    <li><a href="#">Contact Us</a></li>
                                </ul>
                            </div>
                            <div class="col-lg-3">
                                <h2 class="footer-heading mb-4">Resources</h2>
                                <ul class="list-unstyled">
                                    <li><a href="#">About Us</a></li>
                                    <li><a href="#">Testimonials</a></li>
                                    <li><a href="#">Terms of Service</a></li>
                                    <li><a href="#">Privacy</a></li>
                                    <li><a href="#">Contact Us</a></li>
                                </ul>
                            </div>
                            <div class="col-lg-3">
                                <h2 class="footer-heading mb-4">Support</h2>
                                <ul class="list-unstyled">
                                    <li><a href="#">About Us</a></li>
                                    <li><a href="#">Testimonials</a></li>
                                    <li><a href="#">Terms of Service</a></li>
                                    <li><a href="#">Privacy</a></li>
                                    <li><a href="#">Contact Us</a></li>
                                </ul>
                            </div>
                            <div class="col-lg-3">
                                <h2 class="footer-heading mb-4">Company</h2>
                                <ul class="list-unstyled">
                                    <li><a href="#">About Us</a></li>
                                    <li><a href="#">Testimonials</a></li>
                                    <li><a href="#">Terms of Service</a></li>
                                    <li><a href="#">Privacy</a></li>
                                    <li><a href="#">Contact Us</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row pt-5 mt-5 text-center">
                    <div class="col-md-12">
                        <div class="border-top pt-5">
                            <p>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                Copyright &copy;
                                <script>document.write(new Date().getFullYear());</script> All rights reserved | This
                                template is made
                                with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a
                                    href="https://colorlib.com" target="_blank">Colorlib</a>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            </p>
                        </div>
                    </div>

                </div>
            </div>
        </footer>

    </div>





    <script src='{% static "js/popper.min.js" %}'></script>
    <script src='{% static "js/bootstrap.min.js" %}'></script>
    <script src='{% static "js/owl.carousel.min.js" %}'></script>
    <script src='{% static "js/jquery.sticky.js" %}'></script>
    <script src='{% static "js/jquery.waypoints.min.js" %}'></script>
    <script src='{% static "js/jquery.animateNumber.min.js" %}'></script>
    <script src='{% static "js/jquery.fancybox.min.js" %}'></script>
    <script src='{% static "js/jquery.easing.1.3.js" %}'></script>
    <script src='{% static "js/bootstrap-datepicker.min.js" %}'></script>
    <script src='{% static "js/aos.js" %}'></script>

    <script src='{% static "js/main.js" %}'></script>


</body>

</html>