dr_go/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name='main'
urlpatterns = [
    path('',views.index, name="index"),
    # path('about/',views.about,name='about'),
    path('blog/',views.blog,name='blog'),
    path('listing/',views.listing,name='listing'), #나중에 없앨것
    path('main/',views.main,name='main'),
    path('single/',views.single,name='single'),
    path('testimonials/',views.testimonials,name='testimonials'),
    path('contact/',views.contact,name='contact'),
    path('xlsx/',views.xlsx, name='xlsx'),

    path('cities',views.read_city_list,name='read_city_list'),
    path('cities/<str:city>/hospitals',views.read_hospital_list,name='read_hospital_list'),
    path('cities/<str:city>/hospitals/<int:hospital_id>/subjects',views.read_subjects_list,name='read_subjects_list'),
    path('about/<int:subjects_id>',views.about,name='about'),
    path('review/<int:subjects_id>',views.review,name='review'),
    path('review/<int:subjects_id>',views.add_review, name="add_review"),
    
    path('city_list/',views.read_city_list,name='city_list'),  #index.html
    path('<str:city>/hospital_list',views.read_hospital_list,name='hospital_list'),
    path('<int:hospital_id>/subjects_list',views.read_subjects_list,name='read_subjects_list'),
    path('about/<int:subjects_id>',views.about, name='about'),
    path('listing/cities/<str:city>/hospitals', views.listing_hospital, name='listing_hospital'),
    path('cities/all/hospitals', views.listing_all, name='listing_all'),
    


]
# http://127.0.0.1:8000/main/country/
# http://127.0.0.1:8000/main/all/
# http://127.0.0.1:8000/main/seoul/
# http://127.0.0.1:8000/main/about/70

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Hospital(models.Model):
    hospital_name = models.CharField(max_length=20)
    city = models.CharField(max_length=10)
    address = models.CharField(max_length=100)
    callnum = models.CharField(max_length=20)
    url = models.CharField(max_length=50)
    established_on= models.DateField()
    employees_cnt= models.IntegerField()
    count_subject = models.IntegerField()
    count_majordoctor = models.IntegerField()
    count_resident = models.IntegerField()
    count_intern = models.IntegerField()
    image = models.ImageField(blank=True)
    def __str__(self):
        return f'병원명 : {self.hospital_name} / 위치 : {self.city} / 설립일 : {self.established_on}'

class Subjects(models.Model):
    hospital = models.ForeignKey(Hospital , on_delete=models.CASCADE)
    subjects_name = models.CharField(max_length=20)
    specialist_cnt = models.IntegerField()
    image = models.ImageField(blank=True)
    def __str__(self):
        return f'병원명 : {self.hospital.hospital_name} / 진료과목 : {self.subjects_name} / 전문의 수 : {self.specialist_cnt}'
    

class Review(models.Model):
    subjects = models.ForeignKey(Subjects , on_delete=models.CASCADE)
    doctor_name = models.CharField(max_length=10)
    contents = models.TextField()
    speed = models.IntegerField()
    kindness = models.IntegerField()
    responsibility = models.IntegerField()
    professionality = models.IntegerField()
    liked_users = models.ManyToManyField(User, related_name='liked_reviews')
    disliked_users = models.ManyToManyField(User, related_name='disliked_reviews')
    def __str__(self):
        return f'병원명 : {self.subjects.hospital.hospital_name} / 진료과목 : {self.subjects.subjects_name} / 내용 : {self.contents}'

# Create your models here.

main/views.py
from django.shortcuts import render,redirect
from .models import Hospital
from .models import Subjects
from .models import Review
from django.utils import timezone
from django.http import HttpResponse
import pandas as pd
import math
import os
import datetime
# from django.core import serializers
# from .serializers import HospitalSerializer
import json


def index(request):
    context={}
    # print(request.GET)
    # print(request.GET['area'])
    return render(request,'main/index.html',context)

def read_city_list(request):
    city_list = Hospital.objects.values('city').distinct()
    # print(hospitals)
    # 걍 장고 시리얼라이저 사용
    # hospitals_json = serializers.serialize('json',hospitals)
    # print(hospitals_json)

    #장고 rest Framework에서 시리얼라이저 재정의해서 사용
    # hospitals_json = HospitalSerializer(hospitals,many=True)
    # print(hospitals_json)

    #걍 장고 json.dumps
    city_list_json = json.dumps(list(city_list))
    # print(hospitals_json)
    return HttpResponse(city_list_json,content_type="text/json-comment-filtered")

def read_hospital_list(request,city):
    if city == '전체지역':
        hospital_list = Hospital.objects.values('id','hospital_name')
        print(hospital_list)
        hospital_list_json =  json.dumps(list(hospital_list))
        return HttpResponse(hospital_list_json,content_type="text/json-comment-filtered")

    hospital_list = Hospital.objects.values('id','hospital_name').filter(city=city)
    print(hospital_list)
    hospital_list_json =  json.dumps(list(hospital_list))
    return HttpResponse(hospital_list_json,content_type="text/json-comment-filtered")

def read_subjects_list(request,city,hospital_id):
    #hospital_id가 모든 테이블에서 유일하기 때문에 굳이 filter에 city를 안넣어도 된다.
    subjects_list = Subjects.objects.values('id','subjects_name').filter(hospital_id=hospital_id)
    subjects_list_json = json.dumps(list(subjects_list))
    return HttpResponse(subjects_list_json,content_type="text/json-comment-filtered")
    # subjects_list_json ={
    #     {'id' : 1,
    #     'subject_name': 신경의학과},
    #     {

    #     },
    #     {

    #     }


    # }
    



def about(request,subjects_id):
    print(subjects_id)
    subject=Subjects.objects.filter(id=subjects_id)
    print(subject)
    context={'subject':subject}
    return render(request,'main/about.html',context)


    # return HttpResponse() -> 데이터(json) 만 전달할때,
    # return render() -> 데이터(.json) 랑 화면(.html)을 같이 엮어서 전달
    # return render(subjects_list_json, a.html , )
    # return redirect() -> 화면만 

# def about(request,subjects_id):
#     print(subjects_id)
#     subject=Subjects.objects.filter(id=subjects_id)
#     print(subject)
#     context={'subject':subject}
#     # context={'id':subject['id']}
#     return render(request,'main/about.html',context)


def blog(request):
    context={}
    return render(request,'main/blog.html',context)

# def sign_up(request):
#     context={}
#     return render(request,'main/sign_up.html',context)

# def login(request):
#     context={}
#     return render(request,'main/login.html',context)

def about(request,subjects_id):
    print(subjects_id)
    subject=Subjects.objects.filter(id=subjects_id)
    print(subject)
    context={'subject':subject}
    return render(request,'main/about.html',context)

def listing(request):
    print("adfdsfsdfasdfsdaf")
    hospitals=Hospital.objects.all
    context={'hospitals' : hospitals }
    return render(request,'main/listing.html',context) 

# http://고사부.com/main/cities/<str:city>/hospitals' (http://127.0.0.1:8000/main/cities/서울/hospitals)
def listing_hospital(request,city):
    if city == "전체지역":
        hospitals=Hospital.objects.all
        context={'hospitals' : hospitals }
        return render(request,"main/listing.html",context)
    print(city)
    hospitals=Hospital.objects.filter(city=city)  #만든변수=DB테이블명.objects.filter(DB칼럼명=def에서정의한변수)
    # Subjects=Subjects.objects.all
    print(hospitals)
    context={ 'hospitals' :   hospitals  } #{key:value}에서 key값은 아무거나 해줘도 된다. -> 이 key는 html에서 사용한다.
    return render(request,'main/listing_hospital.html',context)

# http://고사부.com/main/cities/all/hospitals  (http://127.0.0.1:8000/main/cities/all/hospitals)
def listing_all(request):
    hospitals=Hospital.objects.all()
    context={'hospitals' : hospitals }
    return render(request,'main/listing_all.html',context)    

def main(request):
    context={}
    return render(request,'main/main.html',context)

def single(request):
    context={}
    return render(request,'main/single.html',context)

def testimonials(request):
    context={}
    return render(request,'main/testimonials.html',context)

def contact(request):
    context={}
    return render(request,'main/contact.html')

def review(request,subjects_id):
    if request.method == "GET":
        subjects=Subjects.objects.filter(id=subjects_id)
        print(subjects)
        hospital_id=Subjects.objects.values('hospital_id').filter(id=subjects_id)
        print(hospital_id)

        hospital=Hospital.objects.filter(id=hospital_id)
        print(hospital)
        context={'subjects': subjects,
                'hospital' : hospital
        }
        print(context)
        return render(request,'main/review.html' ,context)

def add_review(request,subjects_id):
    
    context={}
    return render(request,'main/index.html')

def xlsx(request):
    path=os.path.abspath(os.path.dirname(__file__))+'\\'
    xlsx = pd.read_excel(path+'mockup.xlsx')
    for i in range(len(xlsx)):
        print("xlsx is being read")
        hospital_name = xlsx['요양기관명'][i] 
        city = xlsx['시도명'][i] 
        address = xlsx['주소'][i] 
        callnum = xlsx['전화번호'][i] 
        url = xlsx['병원URL'][i] 
        _date = xlsx['평균 : 개설일자'][i]
        established_on=datetime.datetime.strptime(str(_date),"%Y%m%d").date() 
        employees_cnt = xlsx['합계 : 의사총수'][i] 

        subjects_name = xlsx['진료과목코드명'][i] 
        specialist_cnt = xlsx['합계 : 과목별 전문의수'][i]

        if isinstance(hospital_name,str) == True:
            hospital=Hospital.objects.create(hospital_name=hospital_name,city=city,address =address,callnum=callnum,url= url,established_on=established_on,employees_cnt=employees_cnt)
        Subjects.objects.create(hospital=hospital,subjects_name=subjects_name,specialist_cnt=specialist_cnt)

    print("reading xlsx is done")
    return HttpResponse("xlsx read done")

main/templates/main/about.html
{% extends 'base.html' %}
{% load static %}

{% block content%}

{{subject.0.subjects_name}}

  <div class="hero inner-page" style="background-image: url('../../../static/images/doctor1920.jpg');">

    <div class="container">
      <div class="row align-items-end ">
        <div class="col-lg-5">

          <div class="intro">
            <h1><strong>About</strong></h1>
            <div class="custom-breadcrumbs"><a href='{% url "main:index" %}'>Home</a> <span class="mx-2">/</span>
              <strong>About</strong></div>
          </div>

        </div>
      </div>
    </div>
  </div>



  <div class="site-section">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 mb-5 mb-lg-0 order-lg-2">
          <img src='{% static "images/hero_2.jpg" %}' alt="Image" class="img-fluid rounded">
        </div>
        <div class="col-lg-4 mr-auto">
          <h2>Car Company</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit suscipit, repudiandae similique accusantium
            eius nulla quam laudantium sequi.</p>
          <p>Debitis voluptates corporis saepe molestias tenetur ab quae, quo earum commodi, laborum dolore, fuga
            aliquid delectus cum ipsa?</p>
        </div>
      </div>
    </div>
  </div>

  <div class="site-section bg-light">
    <div class="container">
      <div class="row justify-content-center text-center mb-5 section-2-title">
        <div class="col-md-6">
          <h2 class="mb-4">Meet Our Team</h2>
        </div>
      </div>
      <div class="row align-items-stretch">

        <div class="col-lg-4 col-md-6 mb-5">
          <div class="post-entry-1 h-100 person-1">

            <img src='{% static "images/person_1.jpg" %}' alt="Image" class="img-fluid">

            <div class="post-entry-1-contents">
              <span class="meta">Founder</span>
              <h2>James Doe</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, sapiente.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 mb-5">
          <div class="post-entry-1 h-100 person-1">

            <img src='{% static "images/person_2.jpg" %}' alt="Image" class="img-fluid">

            <div class="post-entry-1-contents">
              <span class="meta">Founder</span>
              <h2>James Doe</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, sapiente.</p>
            </div>
          </div>
        </div>

        <div class="col-lg-4 col-md-6 mb-5">
          <div class="post-entry-1 h-100 person-1">

            <img src='{% static "images/person_3.jpg" %}' alt="Image" class="img-fluid">

            <div class="post-entry-1-contents">
              <span class="meta">Founder</span>
              <h2>James Doe</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, sapiente.</p>
            </div>
          </div>
        </div>

        <div class="col-lg-4 col-md-6 mb-5">
          <div class="post-entry-1 h-100 person-1">

            <img src='{% static "images/person_4.jpg" %}' alt="Image" class="img-fluid">

            <div class="post-entry-1-contents">
              <span class="meta">Founder</span>
              <h2>James Doe</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, sapiente.</p>
            </div>
          </div>
        </div>

        <div class="col-lg-4 col-md-6 mb-5">
          <div class="post-entry-1 h-100 person-1">

            <img src='{% static "images/person_5.jpg" %}' alt="Image" class="img-fluid">

            <div class="post-entry-1-contents">
              <span class="meta">Founder</span>
              <h2>James Doe</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, sapiente.</p>
            </div>
          </div>
        </div>

        <div class="col-lg-4 col-md-6 mb-5">
          <div class="post-entry-1 h-100 person-1">

            <img src='{% static "images/person_1.jpg" %}' alt="Image" class="img-fluid">

            <div class="post-entry-1-contents">
              <span class="meta">Founder</span>
              <h2>James Doe</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, sapiente.</p>
            </div>
          </div>
        </div>


      </div>
    </div>
  </div>

  <div class="site-section">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 mb-5 mb-lg-0">
          <img src='{% static "images/hero_1.jpg" %}' alt="Image" class="img-fluid rounded">
        </div>
        <div class="col-lg-4 ml-auto">
          <h2>Our History</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit suscipit, repudiandae similique accusantium
            eius nulla quam laudantium sequi.</p>
          <p>Debitis voluptates corporis saepe molestias tenetur ab quae, quo earum commodi, laborum dolore, fuga
            aliquid delectus cum ipsa?</p>
        </div>
      </div>
    </div>
  </div>


  <div class="site-section bg-primary py-5">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-7 mb-4 mb-md-0">
          <h2 class="mb-0 text-white">What are you waiting for?</h2>
          <p class="mb-0 opa-7">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati, laboriosam.</p>
        </div>
        <div class="col-lg-5 text-md-right">
          <a href="#" class="btn btn-primary btn-white">Rent a car now</a>
        </div>
      </div>
    </div>
  </div>

  
{% endblock %}

main/templates/main/blog.html
{% extends 'base.html' %}
{% load static %}

{% block content%}

  <div class="hero inner-page" style="background-image: url('../../../static/images/doctor1920.jpg');">

    <div class="container">
      <div class="row align-items-end ">
        <div class="col-lg-5">

          <div class="intro">
            <h1><strong>Reviews</strong></h1>
            <div class="custom-breadcrumbs"><a href='{% url "main:index" %}'>Home</a> <span class="mx-2">/</span>
              <strong>Reviews</strong></div>
          </div>

        </div>
      </div>
    </div>
  </div>



  <div class="site-section bg-light">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-md-6 mb-4">
          <div class="post-entry-1 h-100">
            <a href='{% url "main:single" %}'>
              <img src='{% static "images/post_1.jpg" %}' alt="Image" class="img-fluid">
            </a>
            <div class="post-entry-1-contents">

              <h2><a href='{% url "main:single" %}'>The best car rent in the entire planet</a></h2>
              <span class="meta d-inline-block mb-3">July 17, 2019 <span class="mx-2">by</span> <a
                  href="#">Admin</a></span>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores eos soluta, dolore harum molestias
                consectetur.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 mb-4">
          <div class="post-entry-1 h-100">
            <a href='{% url "main:single" %}'>
              <img src='{% static "images/img_2.jpg" %}' alt="Image" class="img-fluid">
            </a>
            <div class="post-entry-1-contents">

              <h2><a href='{% url "main:single" %}'>The best car rent in the entire planet</a></h2>
              <span class="meta d-inline-block mb-3">July 17, 2019 <span class="mx-2">by</span> <a
                  href="#">Admin</a></span>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores eos soluta, dolore harum molestias
                consectetur.</p>
            </div>
          </div>
        </div>

        <div class="col-lg-4 col-md-6 mb-4">
          <div class="post-entry-1 h-100">
            <a href='{% url "main:single" %}'>
              <img src='{% static "images/img_3.jpg" %}' alt="Image" class="img-fluid">
            </a>
            <div class="post-entry-1-contents">

              <h2><a href='{% url "main:single" %}'>The best car rent in the entire planet</a></h2>
              <span class="meta d-inline-block mb-3">July 17, 2019 <span class="mx-2">by</span> <a
                  href="#">Admin</a></span>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores eos soluta, dolore harum molestias
                consectetur.</p>
            </div>
          </div>
        </div>

        <div class="col-lg-4 col-md-6 mb-4">
          <div class="post-entry-1 h-100">
            <a href='{% url "main:single" %}'>
              <img src='{% static "images/post_1.jpg" %}' alt="Image" class="img-fluid">
            </a>
            <div class="post-entry-1-contents">

              <h2><a href='{% url "main:single" %}'>The best car rent in the entire planet</a></h2>
              <span class="meta d-inline-block mb-3">July 17, 2019 <span class="mx-2">by</span> <a
                  href="#">Admin</a></span>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores eos soluta, dolore harum molestias
                consectetur.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 mb-4">
          <div class="post-entry-1 h-100">
            <a href='{% url "main:single" %}'>
              <img src='{% static "images/img_2.jpg" %}' alt="Image" class="img-fluid">
            </a>
            <div class="post-entry-1-contents">

              <h2><a href='{% url "main:single" %}'>The best car rent in the entire planet</a></h2>
              <span class="meta d-inline-block mb-3">July 17, 2019 <span class="mx-2">by</span> <a
                  href="#">Admin</a></span>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores eos soluta, dolore harum molestias
                consectetur.</p>
            </div>
          </div>
        </div>

        <div class="col-lg-4 col-md-6 mb-4">
          <div class="post-entry-1 h-100">
            <a href='{% url "main:single" %}'>
              <img src='{% static "images/img_3.jpg" %}' alt="Image" class="img-fluid">
            </a>
            <div class="post-entry-1-contents">

              <h2><a href='{% url "main:single" %}'>The best car rent in the entire planet</a></h2>
              <span class="meta d-inline-block mb-3">July 17, 2019 <span class="mx-2">by</span> <a
                  href="#">Admin</a></span>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores eos soluta, dolore harum molestias
                consectetur.</p>
            </div>
          </div>
        </div>

      </div>

      <div class="row">
        <div class="col-5">
          <div class="custom-pagination">
            <a href="#">1</a>
            <span>2</span>
            <a href="#">3</a>
            <a href="#">4</a>
            <a href="#">5</a>
          </div>
        </div>
      </div>

    </div>
  </div>

  <div class="site-section bg-primary py-5">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-7 mb-4 mb-md-0">
          <h2 class="mb-0 text-white">What are you waiting for?</h2>
          <p class="mb-0 opa-7">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati, laboriosam.</p>
        </div>
        <div class="col-lg-5 text-md-right">
          <a href="#" class="btn btn-primary btn-white">Rent a car now</a>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

main/templates/main/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content%}

      <div class="hero inner-page" style="background-image: url('../../../static/images/doctor1920.jpg');">
        
        <div class="container">
          <div class="row align-items-end ">
            <div class="col-lg-5">

              <div class="intro">
                <h1><strong>About</strong></h1>
                <div class="custom-breadcrumbs"><a href='{% url "main:index" %}'>Home</a> <span class="mx-2">/</span> <strong>About</strong></div>
              </div>

            </div>
          </div>
        </div>
      </div>

    

    <div class="site-section bg-light" id="contact-section">
      <div class="container">
        <div class="row justify-content-center text-center">
        <div class="col-7 text-center mb-5">
          <h2>Contact Us Or Use This Form To Rent A Car</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo assumenda, dolorum necessitatibus eius earum voluptates sed!</p>
        </div>
      </div>
        <div class="row">
          <div class="col-lg-8 mb-5" >
            <form action="#" method="post">
              <div class="form-group row">
                <div class="col-md-6 mb-4 mb-lg-0">
                  <input type="text" class="form-control" placeholder="First name">
                </div>
                <div class="col-md-6">
                  <input type="text" class="form-control" placeholder="First name">
                </div>
              </div>

              <div class="form-group row">
                <div class="col-md-12">
                  <input type="text" class="form-control" placeholder="Email address">
                </div>
              </div>

              <div class="form-group row">
                <div class="col-md-12">
                  <textarea name="" id="" class="form-control" placeholder="Write your message." cols="30" rows="10"></textarea>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-md-6 mr-auto">
                  <input type="submit" class="btn btn-block btn-primary text-white py-3 px-5" value="Send Message">
                </div>
              </div>
            </form>
          </div>
          <div class="col-lg-4 ml-auto">
            <div class="bg-white p-3 p-md-5">
              <h3 class="text-black mb-4">Contact Info</h3>
              <ul class="list-unstyled footer-link">
                <li class="d-block mb-3">
                  <span class="d-block text-black">Address:</span>
                  <span>34 Street Name, City Name Here, United States</span></li>
                <li class="d-block mb-3"><span class="d-block text-black">Phone:</span><span>+1 242 4942 290</span></li>
                <li class="d-block mb-3"><span class="d-block text-black">Email:</span><span>info@yourdomain.com</span></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

main/templates/main/listing.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- 
{{hospitals.0}}
{{hospitals.0.hospital_name}} -->

<!-- {% for hospital in hospitals %}
name : {{hospital.hospital_name}} | location : {{hospital.url}}
{% endfor %} -->

<!--병원리스트 타이틀-->
<div class="hero inner-page" style="background-image: url('/../../static/images/doctor1920.jpg');">

  <div class="container">
    <div class="row align-items-end ">
      <div class="col-lg-5">

        <div class="intro">
          <h1><strong>Hospitals</strong></h1>

          <div class="custom-breadcrumbs"><a href='{% static "index.html" %}'>Home</a> <span class="mx-2">/</span>
            <strong>Hospital listings</strong></div>
        </div>

      </div>
    </div>
  </div>
</div>


<!--병원리스트 설명 및 주석-->
<div class="site-section bg-light">
  <div class="container">
    <div class="row">
      <div class="col-lg-7">
        <h2 class="section-heading"><strong>Hospital Listings</strong></h2>
        <p class="mb-5">Find an advanced general hospital for you.</p>
      </div>
    </div>


<!-- 42개의 상급 종합병원 리스트 전체 보여주기-->
    <div class="row">
   
      {% for hospital in hospitals %}

          <div class="col-md-6 col-lg-4 mb-4">
            <div class="listing d-block  align-items-stretch">
              <div class="listing-img h-100 mr-4">
              <!-- <img src='{#% static "images/car_6.jpg" %}' alt="Image" class="img-fluid"> -->
              {% if hospital.image %} 
                <img src='{{hospital.image.url}}' alt="Image" style = 'width: 300px; height: 250px'>
              {% else%}
                <div>사진없음</div>
              {% endif %}
              </div>
                <div class="listing-contents h-100">
                  <h3>  {{hospital.hospital_name}} </h3>
                  <div class="rent-price">
                    <strong>{{hospital.city}}</strong><span class="mx-1"></span>{{hospital.callnum}}
                </div>
                  <div class="d-block d-md-flex mb-3 border-bottom pb-3">
                    <div class="listing-feature pr-4">
                      <span class="caption">진료과목</span>
                      <span class="number">{{hospital.count_subject}}</span>
                    </div>
                    <div class="listing-feature pr-4">
                      <span class="caption">전문의</span>
                      <span class="number">{{hospital.count_majordoctor}}</span>
                    </div>
                    <div class="listing-feature pr-4">
                      <span class="caption">레지던트</span>
                      <span class="number">{{hospital.count_resident}}</span>
                    </div>
                  </div>
                  <div>
                    <p>{{hospital.url}}</p>
                   <!-- <p><a href="#" class="btn btn-primary btn-sm">GO</a></p> -->
                  </div>
                </div>
              </div>
            </div>

            {% endfor %}
    

 <!--마지막 페이지 번호 버튼-->
    </div>
    <div class="row">
      <div class="col-5">
        <div class="custom-pagination">
          <a href="#">1</a> 
          <a href="#">2</a> 
          <!--<span>2</span> -->
          <a href="#">3</a>
          <a href="#">4</a>
          <a href="#">5</a>
        </div>
      </div>
    </div>
  </div>
</div> 

<!--마지막 파란색 마무리글-->
<div class="site-section bg-primary py-5">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-7 mb-4 mb-md-0">
        <h2 class="mb-0 text-white">For a healthy and happy life for all</h2>
        <p class="mb-0 opa-7">모두 건강하고 행복한 하루되세요</p>
      </div>
      <div class="col-lg-5 text-md-right">
        <a href="#" class="btn btn-primary btn-white">doctor.go</a>  <!-- href="#' 이면 맨위로 넘어감-->
      </div>
    </div>
  </div>
</div>

{% endblock %}

main/templates/main/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>